### ISSUE TITLE
Package not found on raspbian

### ISSUE THREAD

**Issue by jromang** [piface/pifacecad-emulator#1]
The installation command fails (package not found): 
pi@raspberrypi ~ $ sudo apt-get install python3-pifacecad-emulator
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances  
Lecture des informations d'état... Fait
E: Impossible de trouver le paquet python3-pifacecad-emulator

It seems a python-pifacecad-emulator package exists (without the '3') but when installed the python module is not found : 
python3
Python 3.2.3 (default, Mar  1 2013, 11:53:50) 
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.

> > > import pifacecad_emulator
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > > ImportError: No module named pifacecad_emulator
> > > quit()

**Comment by GraspGG** [comment]
Hello all,

same issue here:

$ sudo apt-get install python3-pifacedigital-emulator

> > E: Paket python3-pifacecad-emulator kann nicht gefunden werden.

$ sudo apt-get install python-pifacedigital-emulator

> > The package does install without argueing, but not as mentioned (should be python3, shouldn't it?)

$ pifacecad-emulator

> > -bash: pifacecad-emulator: Kommando nicht gefunden.

Woul'd be nice having this one propper running :)

**Comment by tompreston** [comment]
Uh-oh! I've submitted the wrong package to my Debian maintainer! Thanks for bringing this to my attention, I'll get him to change it for the Python 3 package right away!

**Comment by tompreston** [comment]
Ok, the packages have been changed around now. `python3-pifacedigital-emulator` should exist and `python-pifacedigital-emulator` should no longer exist.

Make sure you do a `sudo apt-get update` before trying to install.
